[2022-12-16 20:45:00,042] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T20:44:59.330226+00:00 [queued]>
[2022-12-16 20:45:00,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T20:44:59.330226+00:00 [queued]>
[2022-12-16 20:45:00,053] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 20:45:00,053] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 20:45:00,053] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 20:45:00,068] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): extract_data> on 2022-12-16 20:44:59.330226+00:00
[2022-12-16 20:45:00,073] {standard_task_runner.py:52} INFO - Started process 1636 to run task
[2022-12-16 20:45:00,075] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_web_log', 'extract_data', 'manual__2022-12-16T20:44:59.330226+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/process_web_log.py', '--cfg-path', '/tmp/tmpiq7_sqfn', '--error-file', '/tmp/tmpuecchhn7']
[2022-12-16 20:45:00,076] {standard_task_runner.py:80} INFO - Job 12: Subtask extract_data
[2022-12-16 20:45:00,114] {task_command.py:369} INFO - Running <TaskInstance: process_web_log.extract_data manual__2022-12-16T20:44:59.330226+00:00 [running]> on host 7a891c24faa4
[2022-12-16 20:45:00,189] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_web_log
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T20:44:59.330226+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T20:44:59.330226+00:00
[2022-12-16 20:45:00,189] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-16 20:45:00,190] {subprocess.py:74} INFO - Running command: ['bash', '-c', "grep -o '[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}' /the_folder/log.txt > extracted_data.txt"]
[2022-12-16 20:45:00,198] {subprocess.py:85} INFO - Output:
[2022-12-16 20:45:00,201] {subprocess.py:92} INFO - grep: /the_folder/log.txt: No such file or directory
[2022-12-16 20:45:00,201] {subprocess.py:96} INFO - Command exited with return code 2
[2022-12-16 20:45:00,213] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-12-16 20:45:00,216] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_web_log, task_id=extract_data, execution_date=20221216T204459, start_date=20221216T204500, end_date=20221216T204500
[2022-12-16 20:45:00,224] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task extract_data (Bash command failed. The command returned a non-zero exit code 2.; 1636)
[2022-12-16 20:45:00,248] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-16 20:45:00,281] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
