[2022-12-16 21:05:31,462] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:05:30.620016+00:00 [queued]>
[2022-12-16 21:05:31,476] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:05:30.620016+00:00 [queued]>
[2022-12-16 21:05:31,477] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 21:05:31,477] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 21:05:31,477] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 21:05:31,496] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): extract_data> on 2022-12-16 21:05:30.620016+00:00
[2022-12-16 21:05:31,501] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2022-12-16 21:05:31,503] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_web_log', 'extract_data', 'manual__2022-12-16T21:05:30.620016+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/process_web_log.py', '--cfg-path', '/tmp/tmpiv07ghax', '--error-file', '/tmp/tmp78ua33sp']
[2022-12-16 21:05:31,504] {standard_task_runner.py:80} INFO - Job 23: Subtask extract_data
[2022-12-16 21:05:31,547] {task_command.py:369} INFO - Running <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:05:30.620016+00:00 [running]> on host b3fdf538c244
[2022-12-16 21:05:31,612] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_web_log
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T21:05:30.620016+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T21:05:30.620016+00:00
[2022-12-16 21:05:31,613] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-16 21:05:31,613] {subprocess.py:74} INFO - Running command: ['bash', '-c', "grep -o '[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}' echo ./dags/the_log/log.txt > ./dags/the_log/extracted_data.txt"]
[2022-12-16 21:05:31,623] {subprocess.py:85} INFO - Output:
[2022-12-16 21:05:31,625] {subprocess.py:92} INFO - bash: line 1: ./dags/the_log/extracted_data.txt: No such file or directory
[2022-12-16 21:05:31,625] {subprocess.py:96} INFO - Command exited with return code 1
[2022-12-16 21:05:31,638] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-16 21:05:31,641] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_web_log, task_id=extract_data, execution_date=20221216T210530, start_date=20221216T210531, end_date=20221216T210531
[2022-12-16 21:05:31,650] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task extract_data (Bash command failed. The command returned a non-zero exit code 1.; 142)
[2022-12-16 21:05:31,676] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-16 21:05:31,705] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
